/* AUTO-GENERATED by scripts/convert-template.mjs */
export type TemplatePageMeta = {
  route: string;
  file: string;
  slug: string;
  title: string;
  bodyClass: string;
  standalone: boolean;
};

export const TEMPLATE_PAGES: TemplatePageMeta[] = [
  {
    "route": "/",
    "file": "foreclosure-prototype.html",
    "slug": "index",
    "title": "ForeclosureIQ — Distressed Property Intelligence",
    "bodyClass": "",
    "standalone": true
  },
  {
    "route": "/prototype-1",
    "file": "foreclosure-prototype_1.html",
    "slug": "prototype-1",
    "title": "ForeclosureIQ — Distressed Property Intelligence",
    "bodyClass": "",
    "standalone": true
  }
];

export function getTemplateMetaByRoute(route: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.route === route);
}

export function getTemplateMetaBySlug(slug: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.slug === slug);
}
